version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
    - 3.7.0
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
    - 3.6.4
    - 3.6.6
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
  - dependency-name: jasmine-spec-reporter
    versions:
    - 6.0.0
